server:
  http_listen_port: 9080

positions:
  filename: /position/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /logs/syslogs/*log

  - job_name: services
    static_configs:
      - targets:
          - localhost
        labels:
          job: services
          __path__: /docker/containers/*/*log